configfile: "config.yaml"

include: "rules/common.smk"

# 获取全局参数
directories = get_directories(config)

rule all:
    input: get_all(directories, config)

# load rules
if config["process"] == "download_sra":
    include: "rules/download_sra.smk"
elif config["process"] == "sra2fq":
    samples = {sample["srrid"]: sample["rename"] for sample in config["sra"]}
    include: "rules/convert_sra2fq.smk"
elif config["process"] == "wgbs":
    include: "rules/trim.smk"
    include: "rules/bismark.smk"
    #include: "rules/cut_bismark.smk"
    include: "rules/deduplicate.smk"
    include: "rules/extract.smk"

